happy path query on articles
Jord000/News-App-BackEnd pull request #11
Opened 2023-11-22 11:03 UTC by Jord000

2023-11-22 12:29 UTC, nickkagame requested changes
Hi jordan, nice work, but I think there's a bit of confusion. This task is just to be able to filter by topic.   So the util to check that the query tag is correct is a bit unnessecary at this stage.  Also the error behaviours to check for are - Status 200, accepts topic query, e.g. ?topic=coding.
should check that all returned objects have the queried topic.
Status 200, valid topic query, but has no articles responds with an empty array of articles, e.g. ?topic=paper.
Status 404, non-existent topic query, e.g. ?topic=bananas.

You'll have to check that a topic exists in the DB rather than check the query key against a green list.   

I hope this makes sense!

2023-11-22 12:29 UTC, nickkagame commented on __tests__/app.test.js
> +      .get('/api/articles?topic=neverheardofit')
don't this this should be a 200.  This topic doesn't exist! So should be 404 I think

2023-11-22 12:29 UTC, nickkagame commented on __tests__/app.test.js
> +      .get('/api/articles?thisisanerror')
This is not a category that doesn't exist, it's a query label, and should probably not be tested for.  It's just gonna be what is attached as the key to you req.query ({thisisanerror: 'blah blah}).  So I'd remove this test.

2023-11-22 12:29 UTC, nickkagame commented on __tests__/app.test.js
> +      .get('/api/articles?topic=neverheardofit')
Should only be an empty array for a topic that exists but doesn't yet have any articles

2023-11-22 13:30 UTC, Jord000 commented on __tests__/app.test.js
> +      .get('/api/articles?thisisanerror')
thanks Nick I've updated all of these and it should be better now. My only issue is on a query with an invalid query input. Not sure if this should be error handled or if this is just a miss-use of the API and its ok that the default articles are sent back

2023-11-23 09:00 UTC, nickkagame approved these changes
Great work jordan!

2023-11-23 10:38 UTC, merged